from __future__ import annotations

import hashlib
import os
import subprocess
from collections.abc import Iterator
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path

from hubbleops.core.canonical import content_id
from hubbleops.core.errors import ToolingMissing, ToolingTimeout

MAX_SCAN_BYTES = 16 * 1024 * 1024
SNIFF_BYTES = 8192
READ_CHUNK = 1024 * 1024
GIT_TIMEOUT_SECONDS = 30.0

CONTROL_DIRECTORIES = frozenset({".git"})

VENDOR_DIRECTORIES = frozenset(
    {
        ".eggs",
        ".venv",
        ".yarn",
        "Pods",
        "bower_components",
        "dist-packages",
        "eggs",
        "node_modules",
        "site-packages",
        "third_party",
        "thirdparty",
        "vendor",
        "venv",
        "virtualenv",
    }
)

GENERATED_DIRECTORIES = frozenset(
    {
        "__generated__",
        "_generated",
        ".next",
        ".nuxt",
        "build",
        "dist",
        "generated",
        "target",
    }
)

GENERATED_SUFFIXES = (
    "_pb2.py",
    "_pb2_grpc.py",
    "_generated.go",
    ".pb.go",
    ".pb.cc",
    ".pb.h",
    ".g.dart",
    ".generated.ts",
    ".min.js",
    ".min.css",
)

GENERATED_MARKERS = (
    b"@generated",
    b"Code generated by",
    b"DO NOT EDIT",
    b"autogenerated by",
    b"auto-generated by",
    b"automatically generated",
)

MEDIA_SUFFIXES = frozenset(
    {
        ".aac",
        ".avif",
        ".bmp",
        ".eot",
        ".flac",
        ".gif",
        ".heic",
        ".ico",
        ".jpeg",
        ".jpg",
        ".mov",
        ".mp3",
        ".mp4",
        ".ogg",
        ".otf",
        ".pdf",
        ".png",
        ".psd",
        ".svgz",
        ".tif",
        ".tiff",
        ".ttf",
        ".wav",
        ".webm",
        ".webp",
        ".woff",
        ".woff2",
    }
)


class Classification(StrEnum):
    INSIDE = "INSIDE"
    GENERATED = "GENERATED"
    VENDORED = "VENDORED"
    SUBMODULE = "SUBMODULE"
    EXTERNAL_BOUNDARY = "EXTERNAL_BOUNDARY"
    UNSCANNED = "UNSCANNED"


SCANNED_CLASSIFICATIONS = (
    Classification.INSIDE,
    Classification.GENERATED,
    Classification.VENDORED,
    Classification.SUBMODULE,
)


@dataclass(frozen=True, slots=True)
class ClosureEntry:
    path: str
    classification: Classification
    reason: str
    blob_sha: str | None
    size: int | None

    def carries_source(self) -> bool:
        return self.classification in SCANNED_CLASSIFICATIONS


@dataclass(frozen=True, slots=True)
class SourceClosure:
    root: Path
    repo_sha: str | None
    entries: tuple[ClosureEntry, ...]
    control_directories: tuple[str, ...]

    def tree_hash(self) -> str:
        return content_id([[entry.path, entry.blob_sha] for entry in self.entries])

    def by_path(self) -> dict[str, ClosureEntry]:
        return {entry.path: entry for entry in self.entries}

    def scannable(self) -> tuple[ClosureEntry, ...]:
        return tuple(entry for entry in self.entries if entry.carries_source())

    def unscanned(self) -> tuple[ClosureEntry, ...]:
        return tuple(
            entry for entry in self.entries if entry.classification is Classification.UNSCANNED
        )

    def counts(self) -> dict[str, int]:
        counts = {member.value: 0 for member in Classification}
        for entry in self.entries:
            counts[entry.classification.value] += 1
        return counts


@dataclass(frozen=True, slots=True)
class FileProbe:
    blob_sha: str | None
    size: int | None
    binary: bool
    io_error: str | None
    head: bytes


def build(root: Path) -> SourceClosure:
    resolved = root.resolve()
    if not resolved.is_dir():
        raise NotADirectoryError(f"closure root is not a directory: {resolved}")
    submodules = _submodule_prefixes(resolved)
    entries = sorted(
        _walk(resolved, submodules), key=lambda entry: (entry.path, entry.classification.value)
    )
    return SourceClosure(
        root=resolved,
        repo_sha=_repo_sha(resolved),
        entries=tuple(entries),
        control_directories=tuple(
            sorted(name for name in CONTROL_DIRECTORIES if (resolved / name).exists())
        ),
    )


def _walk(root: Path, submodules: frozenset[str]) -> Iterator[ClosureEntry]:
    for dirpath, dirnames, filenames in os.walk(root, topdown=True, followlinks=False):
        here = Path(dirpath)
        kept: list[str] = []
        for name in sorted(dirnames):
            child = here / name
            relative = _relative(root, child)
            if relative in CONTROL_DIRECTORIES or name in CONTROL_DIRECTORIES:
                continue
            if child.is_symlink():
                escape = _symlink_escape(root, child, "directory ")
                if escape is not None:
                    yield ClosureEntry(
                        path=relative,
                        classification=Classification.EXTERNAL_BOUNDARY,
                        reason=escape,
                        blob_sha=None,
                        size=None,
                    )
                continue
            kept.append(name)
        dirnames[:] = kept
        for name in sorted(filenames):
            child = here / name
            yield _classify(root, child, _relative(root, child), submodules)


def _classify(root: Path, path: Path, relative: str, submodules: frozenset[str]) -> ClosureEntry:
    parts = relative.split("/")
    if _under_submodule(relative, submodules):
        probe = _probe(path)
        return ClosureEntry(
            path=relative,
            classification=Classification.SUBMODULE,
            reason="inside a git submodule; a separate tree with its own proof scope",
            blob_sha=probe.blob_sha,
            size=probe.size,
        )
    if path.is_symlink():
        escape = _symlink_escape(root, path, "")
        if escape is not None:
            return ClosureEntry(
                path=relative,
                classification=Classification.EXTERNAL_BOUNDARY,
                reason=escape,
                blob_sha=None,
                size=None,
            )
    probe = _probe(path)
    if probe.io_error is not None:
        return ClosureEntry(
            path=relative,
            classification=Classification.UNSCANNED,
            reason=f"io_error: {probe.io_error}",
            blob_sha=None,
            size=None,
        )
    if probe.size is not None and probe.size > MAX_SCAN_BYTES:
        return ClosureEntry(
            path=relative,
            classification=Classification.UNSCANNED,
            reason=f"oversize: {probe.size} bytes exceeds the {MAX_SCAN_BYTES} byte scan budget",
            blob_sha=probe.blob_sha,
            size=probe.size,
        )
    if probe.binary:
        suffix = path.suffix.lower()
        if suffix in MEDIA_SUFFIXES:
            return ClosureEntry(
                path=relative,
                classification=Classification.UNSCANNED,
                reason=(
                    f"binary_media: not decodable as text, and the {suffix} suffix claims a "
                    "media container the scanner cannot read"
                ),
                blob_sha=probe.blob_sha,
                size=probe.size,
            )
        return ClosureEntry(
            path=relative,
            classification=Classification.UNSCANNED,
            reason="binary_opaque: not text, and may carry compiled provider usage",
            blob_sha=probe.blob_sha,
            size=probe.size,
        )
    vendor = next((part for part in parts[:-1] if part in VENDOR_DIRECTORIES), None)
    if vendor is not None:
        return ClosureEntry(
            path=relative,
            classification=Classification.VENDORED,
            reason=f"third-party copy under {vendor}/",
            blob_sha=probe.blob_sha,
            size=probe.size,
        )
    generated = _generated_reason(parts, relative, probe.head)
    if generated is not None:
        return ClosureEntry(
            path=relative,
            classification=Classification.GENERATED,
            reason=generated,
            blob_sha=probe.blob_sha,
            size=probe.size,
        )
    return ClosureEntry(
        path=relative,
        classification=Classification.INSIDE,
        reason="first-party source",
        blob_sha=probe.blob_sha,
        size=probe.size,
    )


def _generated_reason(parts: list[str], relative: str, head: bytes) -> str | None:
    directory = next((part for part in parts[:-1] if part in GENERATED_DIRECTORIES), None)
    if directory is not None:
        return f"generated output under {directory}/"
    for suffix in GENERATED_SUFFIXES:
        if relative.endswith(suffix):
            return f"generated file suffix {suffix}"
    marker = _generated_marker(head)
    if marker is not None:
        return f"generated-code marker {marker!r} in the file header"
    return None


def _generated_marker(head: bytes) -> str | None:
    for marker in GENERATED_MARKERS:
        if marker in head:
            return marker.decode("ascii")
    return None


def _probe(path: Path) -> FileProbe:
    digest = hashlib.sha256()
    total = 0
    binary = False
    head = b""
    first = True
    try:
        with open(path, "rb") as handle:
            while True:
                chunk = handle.read(READ_CHUNK)
                if not chunk:
                    break
                if first:
                    head = chunk[:SNIFF_BYTES]
                    binary = b"\x00" in head
                    first = False
                digest.update(chunk)
                total += len(chunk)
    except OSError as error:
        return FileProbe(None, None, False, f"{type(error).__name__}: {error}", b"")
    return FileProbe(digest.hexdigest(), total, binary, None, head)


def _relative(root: Path, path: Path) -> str:
    return path.relative_to(root).as_posix()


def _inside(root: Path, target: Path) -> bool:
    return target == root or root in target.parents


def _symlink_escape(root: Path, path: Path, prefix: str) -> str | None:
    try:
        target = path.resolve(strict=False)
    except OSError as error:
        return (
            f"{prefix}symlink whose target could not be resolved "
            f"({type(error).__name__}); not followed"
        )
    if _inside(root, target):
        return None
    return f"{prefix}symlink leaving the closure root; not followed"


def _under_submodule(relative: str, submodules: frozenset[str]) -> bool:
    return any(relative == prefix or relative.startswith(f"{prefix}/") for prefix in submodules)


def _submodule_prefixes(root: Path) -> frozenset[str]:
    prefixes: set[str] = set()
    modules = root / ".gitmodules"
    if modules.is_file():
        for line in modules.read_text(encoding="utf-8", errors="replace").splitlines():
            stripped = line.strip()
            if stripped.startswith("path"):
                _, _, value = stripped.partition("=")
                candidate = value.strip().strip('"')
                if candidate:
                    prefixes.add(candidate.replace("\\", "/").rstrip("/"))
    for dirpath, dirnames, _ in os.walk(root, topdown=True, followlinks=False):
        dirnames[:] = sorted(name for name in dirnames if name not in CONTROL_DIRECTORIES)
        here = Path(dirpath)
        if here != root and (here / ".git").is_file():
            prefixes.add(_relative(root, here))
            dirnames.clear()
    return frozenset(prefixes)


def _repo_sha(root: Path) -> str | None:
    if not (root / ".git").exists():
        return None
    try:
        completed = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            timeout=GIT_TIMEOUT_SECONDS,
            check=False,
        )
    except FileNotFoundError as error:
        raise ToolingMissing(
            "git", f"{root} is a git repository but git is not on PATH; repo_sha cannot be bound"
        ) from error
    except subprocess.TimeoutExpired as error:
        raise ToolingTimeout("git", GIT_TIMEOUT_SECONDS) from error
    if completed.returncode != 0:
        return None
    sha = completed.stdout.strip()
    return sha if len(sha) == 40 else None
