from __future__ import annotations

import hashlib
import os
import subprocess
from collections.abc import Iterator
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path

from hubbleops.core.canonical import content_id
from hubbleops.core.errors import ToolingMissing, ToolingTimeout

MAX_SCAN_BYTES = 16 * 1024 * 1024
SNIFF_BYTES = 8192
READ_CHUNK = 1024 * 1024
GIT_TIMEOUT_SECONDS = 30.0

CONTROL_ENTRIES = frozenset({".git"})

ENVIRONMENT_DIRECTORIES = frozenset(
    {
        ".hypothesis",
        ".mypy_cache",
        ".nox",
        ".pytest_cache",
        ".ruff_cache",
        ".tox",
        ".venv",
        "__pycache__",
        "venv",
        "virtualenv",
    }
)

ENVIRONMENT_REASON = "environment_directory"
STATE_OUTPUT_REASON = "state_output"
EXCLUDED_DIRECTORY_REASONS = (f"{ENVIRONMENT_REASON}:", f"{STATE_OUTPUT_REASON}:")

STATE_DIRECTORY = ".hubbleops"

STATE_OUTPUT_DIRECTORIES = frozenset(
    {
        "artifacts",
        "attempts",
        "captures",
        "failures",
        "receipts",
        "toolchain",
        "uv-cache",
    }
)

VENDOR_DIRECTORIES = frozenset(
    {
        ".eggs",
        ".yarn",
        "Pods",
        "bower_components",
        "dist-packages",
        "eggs",
        "node_modules",
        "site-packages",
        "third_party",
        "thirdparty",
        "vendor",
    }
)

GENERATED_DIRECTORIES = frozenset(
    {
        "__generated__",
        "_generated",
        ".next",
        ".nuxt",
        "build",
        "dist",
        "generated",
        "target",
    }
)

GENERATED_SUFFIXES = (
    "_pb2.py",
    "_pb2_grpc.py",
    "_generated.go",
    ".pb.go",
    ".pb.cc",
    ".pb.h",
    ".g.dart",
    ".generated.ts",
    ".min.js",
    ".min.css",
)

GENERATED_MARKERS = (
    "@generated",
    "code generated",
    "do not edit",
    "autogenerated",
    "auto-generated",
    "automatically generated",
)

GENERATED_HEADER_PREFIXES = ("#", "//", "/*", "*", "<!--", "--")

MEDIA_SUFFIXES = frozenset(
    {
        ".aac",
        ".avif",
        ".bmp",
        ".eot",
        ".flac",
        ".gif",
        ".heic",
        ".ico",
        ".jpeg",
        ".jpg",
        ".mov",
        ".mp3",
        ".mp4",
        ".ogg",
        ".otf",
        ".pdf",
        ".png",
        ".psd",
        ".svgz",
        ".tif",
        ".tiff",
        ".ttf",
        ".wav",
        ".webm",
        ".webp",
        ".woff",
        ".woff2",
    }
)


class Classification(StrEnum):
    INSIDE = "INSIDE"
    GENERATED = "GENERATED"
    VENDORED = "VENDORED"
    SUBMODULE = "SUBMODULE"
    EXTERNAL_BOUNDARY = "EXTERNAL_BOUNDARY"
    UNSCANNED = "UNSCANNED"


class FileRole(StrEnum):
    SOURCE = "SOURCE"
    CONFIG = "CONFIG"
    MANIFEST = "MANIFEST"
    DATA = "DATA"
    SNAPSHOT = "SNAPSHOT"
    DOCUMENTATION = "DOCUMENTATION"
    STYLESHEET = "STYLESHEET"
    GENERATED_SOURCE = "GENERATED_SOURCE"
    OPAQUE = "OPAQUE"
    UNKNOWN_ROLE = "UNKNOWN_ROLE"


BULK_ROLES = frozenset({FileRole.DATA, FileRole.SNAPSHOT})

NEVER_COLLAPSED_ROLES = frozenset({FileRole.SOURCE, FileRole.MANIFEST, FileRole.GENERATED_SOURCE})

BULK_DATA_BYTES = 256 * 1024

RECORD_STREAM_SUFFIXES = frozenset(
    {".arrow", ".avro", ".csv", ".jsonl", ".ndjson", ".parquet", ".tsv"}
)

STRUCTURED_SUFFIXES = frozenset({".json", ".yaml", ".yml", ".xml"})

SNAPSHOT_SUFFIXES = frozenset({".ambr", ".approved", ".snap"})

SNAPSHOT_DIRECTORIES = frozenset(
    {"__snapshots__", "cassettes", "fixtures", "recordings", "snapshots", "vcr"}
)

MANIFEST_NAMES = frozenset(
    {
        "berksfile.lock",
        "build.gradle",
        "build.gradle.kts",
        "cargo.lock",
        "cargo.toml",
        "composer.json",
        "composer.lock",
        "gemfile",
        "gemfile.lock",
        "go.mod",
        "go.sum",
        "package-lock.json",
        "package.json",
        "packages.lock.json",
        "pipfile",
        "pipfile.lock",
        "pnpm-lock.yaml",
        "poetry.lock",
        "pom.xml",
        "pyproject.toml",
        "requirements.txt",
        "setup.cfg",
        "setup.py",
        "uv.lock",
        "yarn.lock",
    }
)

MANIFEST_SUFFIXES = frozenset({".csproj", ".fsproj", ".vbproj"})

DOCUMENTATION_SUFFIXES = frozenset({".adoc", ".markdown", ".md", ".rst", ".textile", ".txt"})

STYLESHEET_SUFFIXES = frozenset({".css", ".less", ".sass", ".scss"})

CONFIG_SUFFIXES = frozenset({".cfg", ".conf", ".env", ".ini", ".properties", ".toml"})
ENVIRONMENT_FILE_PREFIX = ".env"

SOURCE_SUFFIXES = frozenset(
    {
        ".c",
        ".cc",
        ".cjs",
        ".cpp",
        ".cs",
        ".go",
        ".h",
        ".hpp",
        ".java",
        ".js",
        ".jsx",
        ".kt",
        ".m",
        ".mjs",
        ".php",
        ".pl",
        ".py",
        ".rb",
        ".rs",
        ".scala",
        ".sh",
        ".sql",
        ".swift",
        ".ts",
        ".tsx",
    }
)


SCANNED_CLASSIFICATIONS = (
    Classification.INSIDE,
    Classification.GENERATED,
    Classification.VENDORED,
    Classification.SUBMODULE,
)


@dataclass(frozen=True, slots=True)
class ClosureEntry:
    path: str
    classification: Classification
    reason: str
    blob_sha: str | None
    size: int | None
    role: FileRole = FileRole.UNKNOWN_ROLE

    def carries_source(self) -> bool:
        return self.classification in SCANNED_CLASSIFICATIONS

    def carries_bulk_data(self) -> bool:
        return self.role in BULK_ROLES

    def carries_analyzable_code(self) -> bool:
        return self.carries_source() and self.role not in BULK_ROLES

    def may_collapse_references(self) -> bool:
        return self.role not in NEVER_COLLAPSED_ROLES


@dataclass(frozen=True, slots=True)
class SourceClosure:
    root: Path
    repo_sha: str | None
    entries: tuple[ClosureEntry, ...]
    control_entries: tuple[str, ...]

    def tree_hash(self) -> str:
        return content_id([[entry.path, entry.blob_sha] for entry in self.entries])

    def by_path(self) -> dict[str, ClosureEntry]:
        return {entry.path: entry for entry in self.entries}

    def unenumerated_directories(self) -> tuple[str, ...]:
        return tuple(
            sorted(
                entry.path
                for entry in self.entries
                if entry.reason.startswith(EXCLUDED_DIRECTORY_REASONS)
            )
        )

    def search_exclusions(self) -> tuple[str, ...]:
        return tuple(sorted({*self.control_entries, *self.unenumerated_directories()}))

    def search_exclusion_globs(self) -> tuple[str, ...]:
        return tuple(
            sorted(
                {
                    *(f"!{name}" for name in self.control_entries),
                    *(f"!{directory}/" for directory in self.unenumerated_directories()),
                }
            )
        )

    def scannable(self) -> tuple[ClosureEntry, ...]:
        return tuple(entry for entry in self.entries if entry.carries_source())

    def unscanned(self) -> tuple[ClosureEntry, ...]:
        return tuple(
            entry for entry in self.entries if entry.classification is Classification.UNSCANNED
        )

    def counts(self) -> dict[str, int]:
        counts = {member.value: 0 for member in Classification}
        for entry in self.entries:
            counts[entry.classification.value] += 1
        return counts

    def role_counts(self) -> dict[str, int]:
        counts = {member.value: 0 for member in FileRole}
        for entry in self.entries:
            counts[entry.role.value] += 1
        return counts

    def analyzable(self) -> tuple[ClosureEntry, ...]:
        return tuple(entry for entry in self.entries if entry.carries_analyzable_code())

    def bulk_data(self) -> tuple[ClosureEntry, ...]:
        return tuple(entry for entry in self.entries if entry.carries_bulk_data())


@dataclass(frozen=True, slots=True)
class FileProbe:
    blob_sha: str | None
    size: int | None
    binary: bool
    io_error: str | None
    head: bytes


def build(root: Path) -> SourceClosure:
    resolved = root.resolve()
    if not resolved.is_dir():
        raise NotADirectoryError(f"closure root is not a directory: {resolved}")
    submodules = _submodule_prefixes(resolved)
    entries = sorted(
        (_with_role(entry) for entry in _walk(resolved, submodules)),
        key=lambda entry: (entry.path, entry.classification.value),
    )
    return SourceClosure(
        root=resolved,
        repo_sha=_repo_sha(resolved),
        entries=tuple(entries),
        control_entries=tuple(
            sorted(name for name in CONTROL_ENTRIES if (resolved / name).exists())
        ),
    )


def _walk(root: Path, submodules: frozenset[str]) -> Iterator[ClosureEntry]:
    base = system_path(root)
    for dirpath, dirnames, filenames in os.walk(base, topdown=True, followlinks=False):
        here = _rebase(root, base, dirpath)
        kept: list[str] = []
        for name in sorted(dirnames):
            child = here / name
            relative = _relative(root, child)
            if _is_control_entry(relative, name):
                continue
            if child.is_symlink():
                yield _directory_symlink(root, child, relative)
                continue
            if name in ENVIRONMENT_DIRECTORIES:
                yield _excluded_directory(
                    relative,
                    f"{ENVIRONMENT_REASON}: {name}/ is a regenerated local toolchain directory",
                )
                continue
            if _is_state_output(relative):
                yield _excluded_directory(
                    relative,
                    f"{STATE_OUTPUT_REASON}: {relative}/ is run output regenerated by every run",
                )
                continue
            kept.append(name)
        dirnames[:] = kept
        for name in sorted(filenames):
            child = here / name
            relative = _relative(root, child)
            if _is_control_entry(relative, name):
                continue
            yield _classify(root, child, relative, submodules)


def _is_control_entry(relative: str, name: str) -> bool:
    return relative in CONTROL_ENTRIES or name in CONTROL_ENTRIES


def _classify(root: Path, path: Path, relative: str, submodules: frozenset[str]) -> ClosureEntry:
    parts = relative.split("/")
    if _under_submodule(relative, submodules):
        probe = _probe(path)
        return ClosureEntry(
            path=relative,
            classification=Classification.SUBMODULE,
            reason="inside a git submodule; a separate tree with its own proof scope",
            blob_sha=probe.blob_sha,
            size=probe.size,
        )
    if path.is_symlink():
        escape = _symlink_escape(root, path, "")
        if escape is not None:
            return ClosureEntry(
                path=relative,
                classification=Classification.EXTERNAL_BOUNDARY,
                reason=escape,
                blob_sha=None,
                size=None,
            )
    probe = _probe(path)
    if probe.io_error is not None:
        return ClosureEntry(
            path=relative,
            classification=Classification.UNSCANNED,
            reason=f"io_error: {probe.io_error}",
            blob_sha=None,
            size=None,
        )
    if probe.size is not None and probe.size > MAX_SCAN_BYTES:
        return ClosureEntry(
            path=relative,
            classification=Classification.UNSCANNED,
            reason=f"oversize: {probe.size} bytes exceeds the {MAX_SCAN_BYTES} byte scan budget",
            blob_sha=probe.blob_sha,
            size=probe.size,
        )
    if probe.binary:
        suffix = path.suffix.lower()
        if suffix in MEDIA_SUFFIXES:
            return ClosureEntry(
                path=relative,
                classification=Classification.UNSCANNED,
                reason=(
                    f"binary_media: not decodable as text, and the {suffix} suffix claims a "
                    "media container the scanner cannot read"
                ),
                blob_sha=probe.blob_sha,
                size=probe.size,
            )
        return ClosureEntry(
            path=relative,
            classification=Classification.UNSCANNED,
            reason="binary_opaque: not text, and may carry compiled provider usage",
            blob_sha=probe.blob_sha,
            size=probe.size,
        )
    vendor = next((part for part in parts[:-1] if part in VENDOR_DIRECTORIES), None)
    if vendor is not None:
        return ClosureEntry(
            path=relative,
            classification=Classification.VENDORED,
            reason=f"third-party copy under {vendor}/",
            blob_sha=probe.blob_sha,
            size=probe.size,
        )
    generated = _generated_reason(parts, relative, probe.head)
    if generated is not None:
        return ClosureEntry(
            path=relative,
            classification=Classification.GENERATED,
            reason=generated,
            blob_sha=probe.blob_sha,
            size=probe.size,
        )
    return ClosureEntry(
        path=relative,
        classification=Classification.INSIDE,
        reason="first-party source",
        blob_sha=probe.blob_sha,
        size=probe.size,
    )


def _role_of(relative: str, classification: Classification, size: int | None) -> FileRole:
    if classification is Classification.UNSCANNED:
        return FileRole.OPAQUE
    if classification is Classification.GENERATED:
        return FileRole.GENERATED_SOURCE
    parts = relative.split("/")
    name = parts[-1].lower()
    suffix = _suffix_of(name)
    if name in MANIFEST_NAMES or suffix in MANIFEST_SUFFIXES:
        return FileRole.MANIFEST
    if name.startswith(ENVIRONMENT_FILE_PREFIX):
        return FileRole.CONFIG
    if suffix in SNAPSHOT_SUFFIXES:
        return FileRole.SNAPSHOT
    directories = {part.lower() for part in parts[:-1]}
    if directories & SNAPSHOT_DIRECTORIES and suffix in STRUCTURED_SUFFIXES:
        return FileRole.SNAPSHOT
    if suffix in RECORD_STREAM_SUFFIXES:
        return FileRole.DATA
    if suffix in STRUCTURED_SUFFIXES and size is not None and size > BULK_DATA_BYTES:
        return FileRole.DATA
    if suffix in DOCUMENTATION_SUFFIXES:
        return FileRole.DOCUMENTATION
    if suffix in STYLESHEET_SUFFIXES:
        return FileRole.STYLESHEET
    if suffix in CONFIG_SUFFIXES or suffix in STRUCTURED_SUFFIXES:
        return FileRole.CONFIG
    if suffix in SOURCE_SUFFIXES:
        return FileRole.SOURCE
    return FileRole.UNKNOWN_ROLE


def _suffix_of(name: str) -> str:
    dot = name.rfind(".")
    return name[dot:] if dot > 0 else ""


def _with_role(entry: ClosureEntry) -> ClosureEntry:
    return ClosureEntry(
        path=entry.path,
        classification=entry.classification,
        reason=entry.reason,
        blob_sha=entry.blob_sha,
        size=entry.size,
        role=_role_of(entry.path, entry.classification, entry.size),
    )


def _is_state_output(relative: str) -> bool:
    parts = relative.split("/")
    return len(parts) == 2 and parts[0] == STATE_DIRECTORY and parts[1] in STATE_OUTPUT_DIRECTORIES


def _excluded_directory(relative: str, reason: str) -> ClosureEntry:
    return ClosureEntry(
        path=relative,
        classification=Classification.UNSCANNED,
        reason=(
            f"{reason}, not repository source; its contents were not enumerated "
            "and do not bind the proof scope"
        ),
        blob_sha=content_id({"excluded_directory": relative}),
        size=None,
    )


def _directory_symlink(root: Path, path: Path, relative: str) -> ClosureEntry:
    escape = _symlink_escape(root, path, "directory ")
    if escape is not None:
        return ClosureEntry(
            path=relative,
            classification=Classification.EXTERNAL_BOUNDARY,
            reason=escape,
            blob_sha=None,
            size=None,
        )
    target = path.resolve(strict=False)
    if not target.is_dir():
        return ClosureEntry(
            path=relative,
            classification=Classification.UNSCANNED,
            reason="directory symlink target is unavailable; not followed",
            blob_sha=None,
            size=None,
        )
    target_relative = _relative(root, target)
    return ClosureEntry(
        path=relative,
        classification=Classification.INSIDE,
        reason=(
            f"directory symlink aliases {target_relative}; target is enumerated at its real path"
        ),
        blob_sha=content_id({"directory_symlink_target": target_relative}),
        size=0,
    )


def _generated_reason(parts: list[str], relative: str, head: bytes) -> str | None:
    directory = next((part for part in parts[:-1] if part in GENERATED_DIRECTORIES), None)
    if directory is not None:
        return f"generated output under {directory}/"
    for suffix in GENERATED_SUFFIXES:
        if relative.endswith(suffix):
            return f"generated file suffix {suffix}"
    marker = _generated_marker(head)
    if marker is not None:
        return f"generated-code marker {marker!r} in the file header"
    return None


def _generated_marker(head: bytes) -> str | None:
    lines = head.decode("utf-8", errors="replace").splitlines()[:5]
    for line in lines:
        stripped = line.strip()
        if not stripped.startswith(GENERATED_HEADER_PREFIXES):
            continue
        lowered = stripped.lower()
        for marker in GENERATED_MARKERS:
            if marker in lowered:
                return marker
    return None


def _probe(path: Path) -> FileProbe:
    digest = hashlib.sha256()
    total = 0
    binary = False
    head = b""
    first = True
    try:
        with open(system_path(path), "rb") as handle:
            while True:
                chunk = handle.read(READ_CHUNK)
                if not chunk:
                    break
                if first:
                    head = chunk[:SNIFF_BYTES]
                    first = False
                binary = binary or b"\x00" in chunk
                digest.update(chunk)
                total += len(chunk)
    except OSError as error:
        return FileProbe(None, None, False, f"{type(error).__name__}: {error}", b"")
    return FileProbe(digest.hexdigest(), total, binary, None, head)


def _rebase(root: Path, base: str, dirpath: str) -> Path:
    if dirpath == base:
        return root
    trailing = dirpath[len(base) :].lstrip("\\/")
    return root / trailing if trailing else root


def system_path(path: Path) -> str:
    if os.name != "nt":
        return str(path)
    resolved = os.path.abspath(str(path))
    if resolved.startswith("\\\\?\\"):
        return resolved
    if resolved.startswith("\\\\"):
        return "\\\\?\\UNC" + resolved[1:]
    return "\\\\?\\" + resolved


def _relative(root: Path, path: Path) -> str:
    return path.relative_to(root).as_posix()


def _inside(root: Path, target: Path) -> bool:
    return target == root or root in target.parents


def _symlink_escape(root: Path, path: Path, prefix: str) -> str | None:
    try:
        target = path.resolve(strict=False)
    except OSError as error:
        return (
            f"{prefix}symlink whose target could not be resolved "
            f"({type(error).__name__}); not followed"
        )
    if _inside(root, target):
        return None
    return f"{prefix}symlink leaving the closure root; not followed"


def _under_submodule(relative: str, submodules: frozenset[str]) -> bool:
    return any(relative == prefix or relative.startswith(f"{prefix}/") for prefix in submodules)


def _submodule_prefixes(root: Path) -> frozenset[str]:
    prefixes: set[str] = set()
    modules = root / ".gitmodules"
    if modules.is_file():
        for line in modules.read_text(encoding="utf-8", errors="replace").splitlines():
            stripped = line.strip()
            if stripped.startswith("path"):
                _, _, value = stripped.partition("=")
                candidate = value.strip().strip('"')
                if candidate:
                    prefixes.add(candidate.replace("\\", "/").rstrip("/"))
    base = system_path(root)
    for dirpath, dirnames, _ in os.walk(base, topdown=True, followlinks=False):
        dirnames[:] = sorted(name for name in dirnames if name not in CONTROL_ENTRIES)
        here = _rebase(root, base, dirpath)
        if here != root and (here / ".git").is_file():
            prefixes.add(_relative(root, here))
            dirnames.clear()
    return frozenset(prefixes)


def _repo_sha(root: Path) -> str | None:
    if not (root / ".git").exists():
        return None
    try:
        completed = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            timeout=GIT_TIMEOUT_SECONDS,
            check=False,
        )
    except FileNotFoundError as error:
        raise ToolingMissing(
            "git", f"{root} is a git repository but git is not on PATH; repo_sha cannot be bound"
        ) from error
    except subprocess.TimeoutExpired as error:
        raise ToolingTimeout("git", GIT_TIMEOUT_SECONDS) from error
    if completed.returncode != 0:
        return None
    sha = completed.stdout.strip()
    return sha if len(sha) == 40 else None
