from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from hubbleops.app import registry
from hubbleops.app.cli import scan_repository
from hubbleops.closure import source_closure
from hubbleops.closure.source_closure import Classification, FileRole
from hubbleops.core.canonical import content_id
from hubbleops.core.observer import ObserverContext
from hubbleops.observe import text

DIGEST_WITHOUT_GENERATED_DIRECTORY = (
    "d861a0b6a1c567dcc9c0d5b8422b60fed95c336c11c3cc1ce9b686d724ae4613"
)


def commit_repository(repository: Path, files: dict[str, str]) -> str:
    repository.mkdir(parents=True)
    for relative, content in files.items():
        (repository / relative).write_text(content, encoding="utf-8")
    for arguments in (
        ("init", "--quiet", "--initial-branch=main"),
        ("config", "user.email", "fixture@hubbleops.test"),
        ("config", "user.name", "HubbleOps Fixture"),
        ("config", "commit.gpgsign", "false"),
        ("add", "--all"),
        ("commit", "--quiet", "-m", "one"),
    ):
        subprocess.run(["git", "-C", str(repository), *arguments], check=True, capture_output=True)
    return subprocess.run(
        ["git", "-C", str(repository), "rev-parse", "HEAD"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()


def add_worktree(repository: Path, worktree: Path, sha: str) -> None:
    subprocess.run(
        ["git", "-C", str(repository), "worktree", "add", "--detach", str(worktree), sha],
        check=True,
        capture_output=True,
    )
    assert (worktree / ".git").is_file()


def observer_context(
    closure: source_closure.SourceClosure, pack: registry.LoadedPack
) -> ObserverContext:
    return ObserverContext(
        provider="_mock",
        run_id=content_id({"run": 1}),
        proof_scope_hash=content_id({"scope": 1}),
        repo_sha=closure.repo_sha,
        dependency_context_hash=None,
        surface=pack.surface,
    )


def ripgrep_search_set(closure: source_closure.SourceClosure) -> set[str]:
    args = [text.ripgrep_binary().path, "--no-config", "--hidden", "--no-ignore", "--files"]
    for glob in closure.search_exclusion_globs():
        args.extend(["-g", glob])
    args.extend(["--", "."])
    listed = subprocess.run(args, cwd=closure.root, capture_output=True, text=True, check=False)
    assert listed.returncode in (0, 1), listed.stderr
    return {
        line.replace("\\", "/").removeprefix("./")
        for line in listed.stdout.splitlines()
        if line.strip()
    }


def build_tree(root: Path) -> None:
    (root / "src").mkdir(parents=True)
    (root / "src" / "app.py").write_text("value = 1\n", encoding="utf-8")
    (root / "node_modules" / "pkg").mkdir(parents=True)
    (root / "node_modules" / "pkg" / "index.js").write_text(
        "module.exports = {};\n", encoding="utf-8"
    )
    (root / "build").mkdir()
    (root / "build" / "out.js").write_text("var x = 1;\n", encoding="utf-8")
    (root / "src" / "schema_pb2.py").write_text("SERIALIZED = b''\n", encoding="utf-8")
    (root / "src" / "marked.py").write_text("# @generated by a tool\nvalue = 2\n", encoding="utf-8")
    (root / "assets").mkdir()
    (root / "assets" / "logo.png").write_bytes(b"\x89PNG\x00\x00binary")
    (root / "assets" / "blob.dat").write_bytes(b"\x00\x01\x02opaque")


def test_every_path_gets_exactly_one_classification(tmp_path: Path) -> None:
    build_tree(tmp_path)
    closure = source_closure.build(tmp_path)
    paths = [entry.path for entry in closure.entries]
    assert len(paths) == len(set(paths))
    assert set(paths) == {
        "assets/blob.dat",
        "assets/logo.png",
        "build/out.js",
        "node_modules/pkg/index.js",
        "src/app.py",
        "src/marked.py",
        "src/schema_pb2.py",
    }


def test_classifications_follow_the_documented_precedence(tmp_path: Path) -> None:
    build_tree(tmp_path)
    by_path = source_closure.build(tmp_path).by_path()
    assert by_path["src/app.py"].classification is Classification.INSIDE
    assert by_path["node_modules/pkg/index.js"].classification is Classification.VENDORED
    assert by_path["build/out.js"].classification is Classification.GENERATED
    assert by_path["src/schema_pb2.py"].classification is Classification.GENERATED
    assert by_path["src/marked.py"].classification is Classification.GENERATED
    assert by_path["assets/logo.png"].classification is Classification.UNSCANNED
    assert by_path["assets/blob.dat"].classification is Classification.UNSCANNED


def build_role_tree(root: Path) -> None:
    (root / "src").mkdir(parents=True)
    (root / "src" / "app.py").write_text("value = 1\n", encoding="utf-8")
    (root / "package.json").write_text('{"name": "app"}\n', encoding="utf-8")
    (root / "pyproject.toml").write_text("[project]\nname = 'app'\n", encoding="utf-8")
    (root / "data").mkdir()
    (root / "data" / "records.jsonl").write_text('{"a": 1}\n', encoding="utf-8")
    (root / "data" / "table.csv").write_text("a,b\n1,2\n", encoding="utf-8")
    (root / "data" / "small.json").write_text('{"a": 1}\n', encoding="utf-8")
    (root / "data" / "big.json").write_text(
        "[" + ",".join('{"a": 1}' for _ in range(40000)) + "]\n", encoding="utf-8"
    )
    (root / "tests" / "__snapshots__").mkdir(parents=True)
    (root / "tests" / "__snapshots__" / "view.json").write_text("{}\n", encoding="utf-8")
    (root / "cassettes").mkdir()
    (root / "cassettes" / "call.yaml").write_text("body: x\n", encoding="utf-8")
    (root / "README.md").write_text("docs\n", encoding="utf-8")
    (root / "settings.ini").write_text("[a]\nb = 1\n", encoding="utf-8")


def test_every_entry_carries_exactly_one_role(tmp_path: Path) -> None:
    build_role_tree(tmp_path)
    closure = source_closure.build(tmp_path)
    assert all(isinstance(entry.role, FileRole) for entry in closure.entries)
    assert sum(closure.role_counts().values()) == len(closure.entries)


def test_roles_separate_data_from_code_and_manifests(tmp_path: Path) -> None:
    build_role_tree(tmp_path)
    by_path = source_closure.build(tmp_path).by_path()
    assert by_path["src/app.py"].role is FileRole.SOURCE
    assert by_path["package.json"].role is FileRole.MANIFEST
    assert by_path["pyproject.toml"].role is FileRole.MANIFEST
    assert by_path["data/records.jsonl"].role is FileRole.DATA
    assert by_path["data/table.csv"].role is FileRole.DATA
    assert by_path["data/big.json"].role is FileRole.DATA
    assert by_path["data/small.json"].role is FileRole.CONFIG
    assert by_path["tests/__snapshots__/view.json"].role is FileRole.SNAPSHOT
    assert by_path["cassettes/call.yaml"].role is FileRole.SNAPSHOT
    assert by_path["README.md"].role is FileRole.DOCUMENTATION
    assert by_path["settings.ini"].role is FileRole.CONFIG


def test_source_and_manifest_roles_are_never_collapsed_or_treated_as_bulk(tmp_path: Path) -> None:
    build_role_tree(tmp_path)
    by_path = source_closure.build(tmp_path).by_path()
    for path in ("src/app.py", "package.json", "pyproject.toml"):
        assert not by_path[path].carries_bulk_data()
        assert not by_path[path].may_collapse_references()
    assert by_path["src/app.py"].carries_analyzable_code()


def test_a_bulk_data_file_is_enumerated_but_not_analyzable_code(tmp_path: Path) -> None:
    build_role_tree(tmp_path)
    closure = source_closure.build(tmp_path)
    by_path = closure.by_path()
    assert by_path["data/records.jsonl"].carries_bulk_data()
    assert not by_path["data/records.jsonl"].carries_analyzable_code()
    assert "data/records.jsonl" in {entry.path for entry in closure.entries}
    assert "data/records.jsonl" in {entry.path for entry in closure.bulk_data()}


def test_binary_media_and_opaque_binaries_are_told_apart(tmp_path: Path) -> None:
    build_tree(tmp_path)
    by_path = source_closure.build(tmp_path).by_path()
    assert by_path["assets/logo.png"].reason.startswith("binary_media")
    assert by_path["assets/blob.dat"].reason.startswith("binary_opaque")


def test_every_entry_carries_a_reason(tmp_path: Path) -> None:
    build_tree(tmp_path)
    for entry in source_closure.build(tmp_path).entries:
        assert entry.reason


def test_submodule_paths_are_classified_from_gitmodules(tmp_path: Path) -> None:
    (tmp_path / "libs" / "shared").mkdir(parents=True)
    (tmp_path / "libs" / "shared" / "core.py").write_text("value = 1\n", encoding="utf-8")
    (tmp_path / ".gitmodules").write_text(
        '[submodule "shared"]\n\tpath = libs/shared\n\turl = https://example.test/shared.git\n',
        encoding="utf-8",
    )
    by_path = source_closure.build(tmp_path).by_path()
    assert by_path["libs/shared/core.py"].classification is Classification.SUBMODULE


def test_a_gitlink_directory_is_a_submodule(tmp_path: Path) -> None:
    (tmp_path / "vendored-repo").mkdir()
    (tmp_path / "vendored-repo" / ".git").write_text(
        "gitdir: ../.git/modules/x\n", encoding="utf-8"
    )
    (tmp_path / "vendored-repo" / "main.py").write_text("value = 1\n", encoding="utf-8")
    by_path = source_closure.build(tmp_path).by_path()
    assert by_path["vendored-repo/main.py"].classification is Classification.SUBMODULE


def test_oversize_files_are_unscanned_not_silently_skipped(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    (tmp_path / "big.txt").write_text("x" * 64, encoding="utf-8")
    monkeypatch.setattr(source_closure, "MAX_SCAN_BYTES", 8)
    entry = source_closure.build(tmp_path).by_path()["big.txt"]
    assert entry.classification is Classification.UNSCANNED
    assert entry.reason.startswith("oversize")


def test_the_git_control_directory_is_reported_not_hidden(tmp_path: Path) -> None:
    (tmp_path / ".git").mkdir()
    (tmp_path / ".git" / "config").write_text("[core]\n", encoding="utf-8")
    (tmp_path / "app.py").write_text("value = 1\n", encoding="utf-8")
    closure = source_closure.build(tmp_path)
    assert [entry.path for entry in closure.entries] == ["app.py"]
    assert closure.control_entries == (".git",)


def test_a_detached_worktree_and_a_working_tree_of_one_commit_share_a_closure(
    tmp_path: Path,
) -> None:
    repository = tmp_path / "repo"
    sha = commit_repository(repository, {"app.py": "value = 1\n"})
    worktree = tmp_path / "worktree"
    add_worktree(repository, worktree, sha)

    working = source_closure.build(repository)
    detached = source_closure.build(worktree)
    assert [entry.path for entry in detached.entries] == [entry.path for entry in working.entries]
    assert detached.tree_hash() == working.tree_hash()
    assert detached.repo_sha == working.repo_sha == sha


def test_tree_hash_binds_content_even_without_git(tmp_path: Path) -> None:
    (tmp_path / "app.py").write_text("value = 1\n", encoding="utf-8")
    first = source_closure.build(tmp_path)
    assert first.repo_sha is None
    assert first.tree_hash() == source_closure.build(tmp_path).tree_hash()
    (tmp_path / "app.py").write_text("value = 2\n", encoding="utf-8")
    assert source_closure.build(tmp_path).tree_hash() != first.tree_hash()


def test_scannable_excludes_unscanned_entries(tmp_path: Path) -> None:
    build_tree(tmp_path)
    closure = source_closure.build(tmp_path)
    assert all(entry.carries_source() for entry in closure.scannable())
    assert len(closure.scannable()) + len(closure.unscanned()) == len(closure.entries)


def test_a_missing_root_is_an_error_not_an_empty_closure(tmp_path: Path) -> None:
    with pytest.raises((NotADirectoryError, FileNotFoundError)):
        source_closure.build(tmp_path / "absent")


def test_a_nul_byte_past_the_sniff_window_still_reads_as_binary(tmp_path: Path) -> None:
    padding = "".join(f"# padding line {index:05d}\n" for index in range(700)).encode()
    assert len(padding) > source_closure.SNIFF_BYTES
    (tmp_path / "src").mkdir(parents=True)
    (tmp_path / "src" / "late.py").write_bytes(padding + b'\x00\nvalue = "v22"\n')

    by_path = {entry.path: entry for entry in source_closure.build(tmp_path).entries}
    assert by_path["src/late.py"].classification is Classification.UNSCANNED
    assert by_path["src/late.py"].reason.startswith("binary_opaque")


def test_an_internal_directory_symlink_is_a_bound_alias_not_a_missing_path(tmp_path: Path) -> None:
    target = tmp_path / "actual"
    target.mkdir()
    (target / "app.py").write_text("value = 1\n", encoding="utf-8")
    alias = tmp_path / "alias"
    try:
        alias.symlink_to(target, target_is_directory=True)
    except OSError as error:
        pytest.skip(f"directory symlinks are unavailable: {error}")

    by_path = source_closure.build(tmp_path).by_path()
    assert by_path["alias"].classification is Classification.INSIDE
    assert by_path["alias"].blob_sha is not None
    assert by_path["actual/app.py"].classification is Classification.INSIDE


def test_environment_directories_are_accounted_but_never_enumerated(tmp_path: Path) -> None:
    build_tree(tmp_path)
    (tmp_path / ".venv" / "lib" / "site-packages" / "dep").mkdir(parents=True)
    (tmp_path / ".venv" / "lib" / "site-packages" / "dep" / "mod.py").write_text(
        "value = 3\n", encoding="utf-8"
    )
    (tmp_path / ".pytest_cache").mkdir()
    (tmp_path / ".pytest_cache" / "lastfailed").write_text("{}\n", encoding="utf-8")

    by_path = source_closure.build(tmp_path).by_path()

    assert by_path[".venv"].classification is Classification.UNSCANNED
    assert by_path[".venv"].reason.startswith("environment_directory: .venv/")
    assert by_path[".pytest_cache"].classification is Classification.UNSCANNED
    enumerated = [path for path in by_path if path.startswith((".venv/", ".pytest_cache/"))]
    assert enumerated == [], f"environment contents must not be enumerated: {enumerated}"


def test_run_output_under_the_state_directory_is_accounted_but_not_enumerated(
    tmp_path: Path,
) -> None:
    build_tree(tmp_path)
    (tmp_path / ".hubbleops" / "artifacts" / "run").mkdir(parents=True)
    (tmp_path / ".hubbleops" / "artifacts" / "run" / "ledger.json").write_text(
        "{}\n", encoding="utf-8"
    )
    (tmp_path / ".hubbleops" / "surface.yml").write_text("rules: []\n", encoding="utf-8")

    by_path = source_closure.build(tmp_path).by_path()

    assert by_path[".hubbleops/artifacts"].classification is Classification.UNSCANNED
    assert by_path[".hubbleops/artifacts"].reason.startswith("state_output:")
    assert ".hubbleops/artifacts/run/ledger.json" not in by_path
    assert by_path[".hubbleops/surface.yml"].classification is Classification.INSIDE


def test_excluded_directory_identity_does_not_depend_on_its_contents(tmp_path: Path) -> None:
    build_tree(tmp_path)
    (tmp_path / ".venv").mkdir()
    (tmp_path / ".venv" / "first.py").write_text("value = 1\n", encoding="utf-8")
    before = source_closure.build(tmp_path).tree_hash()

    (tmp_path / ".venv" / "second.py").write_text("value = 2\n", encoding="utf-8")
    after = source_closure.build(tmp_path).tree_hash()

    assert before == after, "rebuilding a local environment must not invalidate the proof scope"


def test_generated_directories_are_enumerated_and_every_file_under_them_is_generated(
    tmp_path: Path,
) -> None:
    (tmp_path / "build" / "lib" / "pkg").mkdir(parents=True)
    (tmp_path / "build" / "lib" / "pkg" / "client.py").write_text("value = 1\n", encoding="utf-8")
    (tmp_path / "build" / "lib" / "pkg" / "data.json").write_text("{}\n", encoding="utf-8")
    (tmp_path / "dist").mkdir()
    (tmp_path / "dist" / "bundle.js").write_text("var x = 1;\n", encoding="utf-8")
    (tmp_path / "pkg").mkdir()
    (tmp_path / "pkg" / "client.py").write_text("value = 1\n", encoding="utf-8")

    closure = source_closure.build(tmp_path)
    by_path = closure.by_path()

    generated = {path for path in by_path if path.startswith(("build/", "dist/"))}
    assert generated == {"build/lib/pkg/client.py", "build/lib/pkg/data.json", "dist/bundle.js"}
    assert all(by_path[path].classification is Classification.GENERATED for path in generated)
    assert all(by_path[path].role is FileRole.GENERATED_SOURCE for path in generated)
    assert by_path["pkg/client.py"].classification is Classification.INSIDE
    assert closure.search_exclusions() == ()
    assert ripgrep_search_set(closure) == set(by_path)


def test_a_surface_match_under_a_generated_directory_is_accounted_not_a_tooling_stop(
    tmp_path: Path, mock_pack: registry.LoadedPack
) -> None:
    (tmp_path / "build" / "lib" / "pkg").mkdir(parents=True)
    (tmp_path / "build" / "lib" / "pkg" / "client.py").write_text(
        'CLIENT = "mockprov"\n', encoding="utf-8"
    )
    (tmp_path / "pkg").mkdir()
    (tmp_path / "pkg" / "client.py").write_text('CLIENT = "mockprov"\n', encoding="utf-8")

    book = scan_repository(tmp_path, mock_pack).ledger

    statuses: dict[str, set[str]] = {}
    for candidate in book.candidates:
        statuses.setdefault(book.location_of(candidate).path, set()).add(candidate["status"])
    assert statuses["build/lib/pkg/client.py"] == {"EXCLUDED_WITH_EVIDENCE"}
    assert "pkg/client.py" in statuses
    assert book.unexplained() == 0


def test_the_closure_of_a_tree_without_a_generated_directory_keeps_its_digest(
    tmp_path: Path,
) -> None:
    (tmp_path / "src").mkdir()
    (tmp_path / "src" / "app.py").write_text("value = 1\n", encoding="utf-8")
    (tmp_path / "src" / "schema_pb2.py").write_text("SERIALIZED = b''\n", encoding="utf-8")
    (tmp_path / "node_modules" / "pkg").mkdir(parents=True)
    (tmp_path / "node_modules" / "pkg" / "index.js").write_text(
        "module.exports = {};\n", encoding="utf-8"
    )
    (tmp_path / "assets").mkdir()
    (tmp_path / "assets" / "logo.png").write_bytes(b"\x89PNG\x00\x00binary")
    (tmp_path / ".venv").mkdir()
    (tmp_path / ".venv" / "first.py").write_text("value = 1\n", encoding="utf-8")
    (tmp_path / "README.md").write_text("docs\n", encoding="utf-8")

    closure = source_closure.build(tmp_path)

    assert [entry.path for entry in closure.entries] == [
        ".venv",
        "README.md",
        "assets/logo.png",
        "node_modules/pkg/index.js",
        "src/app.py",
        "src/schema_pb2.py",
    ]
    assert closure.tree_hash() == DIGEST_WITHOUT_GENERATED_DIRECTORY


def test_a_worktree_git_pointer_file_is_excluded_from_the_search_like_the_directory(
    tmp_path: Path,
) -> None:
    repository = tmp_path / "mockprov-checkout"
    sha = commit_repository(repository, {"app.py": 'value = "mockprov"\n'})
    worktree = tmp_path / "worktree"
    add_worktree(repository, worktree, sha)
    assert "mockprov" in (worktree / ".git").read_text(encoding="utf-8")

    closure = source_closure.build(worktree)

    assert ".git" not in closure.by_path()
    assert closure.control_entries == (".git",)
    assert closure.search_exclusion_globs() == ("!.git",)
    assert ripgrep_search_set(closure) == {"app.py"}
    assert ripgrep_search_set(source_closure.build(repository)) == {"app.py"}


def test_pruned_directories_keep_directory_only_globs(tmp_path: Path) -> None:
    (tmp_path / ".venv").mkdir()
    (tmp_path / ".venv" / "dep.py").write_text("value = 2\n", encoding="utf-8")
    (tmp_path / "venv").write_text("a file that merely shares a pruned name\n", encoding="utf-8")
    (tmp_path / "app.py").write_text("value = 1\n", encoding="utf-8")

    closure = source_closure.build(tmp_path)

    assert closure.search_exclusion_globs() == ("!.venv/",)
    assert ripgrep_search_set(closure) == {"app.py", "venv"}
    assert closure.by_path()["venv"].classification is Classification.INSIDE


def test_the_text_observer_does_not_stop_on_a_worktree_git_pointer_naming_the_surface(
    tmp_path: Path, mock_pack: registry.LoadedPack
) -> None:
    repository = tmp_path / "mockprov-checkout"
    sha = commit_repository(repository, {"app.py": 'value = "mockprov"\n'})
    worktree = tmp_path / "worktree"
    add_worktree(repository, worktree, sha)
    closure = source_closure.build(worktree)

    records = text.scan(closure, observer_context(closure, mock_pack))

    paths = {str(record["path"]) for record in records}
    assert ".git" not in paths
    assert "app.py" in paths
