from __future__ import annotations

from pathlib import Path

import pytest

from hubbleops.closure import source_closure
from hubbleops.closure.source_closure import Classification


def build_tree(root: Path) -> None:
    (root / "src").mkdir(parents=True)
    (root / "src" / "app.py").write_text("value = 1\n", encoding="utf-8")
    (root / "node_modules" / "pkg").mkdir(parents=True)
    (root / "node_modules" / "pkg" / "index.js").write_text(
        "module.exports = {};\n", encoding="utf-8"
    )
    (root / "build").mkdir()
    (root / "build" / "out.js").write_text("var x = 1;\n", encoding="utf-8")
    (root / "src" / "schema_pb2.py").write_text("SERIALIZED = b''\n", encoding="utf-8")
    (root / "src" / "marked.py").write_text("# @generated by a tool\nvalue = 2\n", encoding="utf-8")
    (root / "assets").mkdir()
    (root / "assets" / "logo.png").write_bytes(b"\x89PNG\x00\x00binary")
    (root / "assets" / "blob.dat").write_bytes(b"\x00\x01\x02opaque")


def test_every_path_gets_exactly_one_classification(tmp_path: Path) -> None:
    build_tree(tmp_path)
    closure = source_closure.build(tmp_path)
    paths = [entry.path for entry in closure.entries]
    assert len(paths) == len(set(paths))
    assert set(paths) == {
        "assets/blob.dat",
        "assets/logo.png",
        "build/out.js",
        "node_modules/pkg/index.js",
        "src/app.py",
        "src/marked.py",
        "src/schema_pb2.py",
    }


def test_classifications_follow_the_documented_precedence(tmp_path: Path) -> None:
    build_tree(tmp_path)
    by_path = source_closure.build(tmp_path).by_path()
    assert by_path["src/app.py"].classification is Classification.INSIDE
    assert by_path["node_modules/pkg/index.js"].classification is Classification.VENDORED
    assert by_path["build/out.js"].classification is Classification.GENERATED
    assert by_path["src/schema_pb2.py"].classification is Classification.GENERATED
    assert by_path["src/marked.py"].classification is Classification.GENERATED
    assert by_path["assets/logo.png"].classification is Classification.UNSCANNED
    assert by_path["assets/blob.dat"].classification is Classification.UNSCANNED


def test_binary_media_and_opaque_binaries_are_told_apart(tmp_path: Path) -> None:
    build_tree(tmp_path)
    by_path = source_closure.build(tmp_path).by_path()
    assert by_path["assets/logo.png"].reason.startswith("binary_media")
    assert by_path["assets/blob.dat"].reason.startswith("binary_opaque")


def test_every_entry_carries_a_reason(tmp_path: Path) -> None:
    build_tree(tmp_path)
    for entry in source_closure.build(tmp_path).entries:
        assert entry.reason


def test_submodule_paths_are_classified_from_gitmodules(tmp_path: Path) -> None:
    (tmp_path / "libs" / "shared").mkdir(parents=True)
    (tmp_path / "libs" / "shared" / "core.py").write_text("value = 1\n", encoding="utf-8")
    (tmp_path / ".gitmodules").write_text(
        '[submodule "shared"]\n\tpath = libs/shared\n\turl = https://example.test/shared.git\n',
        encoding="utf-8",
    )
    by_path = source_closure.build(tmp_path).by_path()
    assert by_path["libs/shared/core.py"].classification is Classification.SUBMODULE


def test_a_gitlink_directory_is_a_submodule(tmp_path: Path) -> None:
    (tmp_path / "vendored-repo").mkdir()
    (tmp_path / "vendored-repo" / ".git").write_text(
        "gitdir: ../.git/modules/x\n", encoding="utf-8"
    )
    (tmp_path / "vendored-repo" / "main.py").write_text("value = 1\n", encoding="utf-8")
    by_path = source_closure.build(tmp_path).by_path()
    assert by_path["vendored-repo/main.py"].classification is Classification.SUBMODULE


def test_oversize_files_are_unscanned_not_silently_skipped(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    (tmp_path / "big.txt").write_text("x" * 64, encoding="utf-8")
    monkeypatch.setattr(source_closure, "MAX_SCAN_BYTES", 8)
    entry = source_closure.build(tmp_path).by_path()["big.txt"]
    assert entry.classification is Classification.UNSCANNED
    assert entry.reason.startswith("oversize")


def test_the_git_control_directory_is_reported_not_hidden(tmp_path: Path) -> None:
    (tmp_path / ".git").mkdir()
    (tmp_path / ".git" / "config").write_text("[core]\n", encoding="utf-8")
    (tmp_path / "app.py").write_text("value = 1\n", encoding="utf-8")
    closure = source_closure.build(tmp_path)
    assert [entry.path for entry in closure.entries] == ["app.py"]
    assert closure.control_directories == (".git",)


def test_tree_hash_binds_content_even_without_git(tmp_path: Path) -> None:
    (tmp_path / "app.py").write_text("value = 1\n", encoding="utf-8")
    first = source_closure.build(tmp_path)
    assert first.repo_sha is None
    assert first.tree_hash() == source_closure.build(tmp_path).tree_hash()
    (tmp_path / "app.py").write_text("value = 2\n", encoding="utf-8")
    assert source_closure.build(tmp_path).tree_hash() != first.tree_hash()


def test_scannable_excludes_unscanned_entries(tmp_path: Path) -> None:
    build_tree(tmp_path)
    closure = source_closure.build(tmp_path)
    assert all(entry.carries_source() for entry in closure.scannable())
    assert len(closure.scannable()) + len(closure.unscanned()) == len(closure.entries)


def test_a_missing_root_is_an_error_not_an_empty_closure(tmp_path: Path) -> None:
    with pytest.raises((NotADirectoryError, FileNotFoundError)):
        source_closure.build(tmp_path / "absent")


def test_a_nul_byte_past_the_sniff_window_still_reads_as_binary(tmp_path: Path) -> None:
    padding = "".join(f"# padding line {index:05d}\n" for index in range(700)).encode()
    assert len(padding) > source_closure.SNIFF_BYTES
    (tmp_path / "src").mkdir(parents=True)
    (tmp_path / "src" / "late.py").write_bytes(padding + b'\x00\nvalue = "v22"\n')

    by_path = {entry.path: entry for entry in source_closure.build(tmp_path).entries}
    assert by_path["src/late.py"].classification is Classification.UNSCANNED
    assert by_path["src/late.py"].reason.startswith("binary_opaque")


def test_an_internal_directory_symlink_is_a_bound_alias_not_a_missing_path(tmp_path: Path) -> None:
    target = tmp_path / "actual"
    target.mkdir()
    (target / "app.py").write_text("value = 1\n", encoding="utf-8")
    alias = tmp_path / "alias"
    try:
        alias.symlink_to(target, target_is_directory=True)
    except OSError as error:
        pytest.skip(f"directory symlinks are unavailable: {error}")

    by_path = source_closure.build(tmp_path).by_path()
    assert by_path["alias"].classification is Classification.INSIDE
    assert by_path["alias"].blob_sha is not None
    assert by_path["actual/app.py"].classification is Classification.INSIDE


def test_environment_directories_are_accounted_but_never_enumerated(tmp_path: Path) -> None:
    build_tree(tmp_path)
    (tmp_path / ".venv" / "lib" / "site-packages" / "dep").mkdir(parents=True)
    (tmp_path / ".venv" / "lib" / "site-packages" / "dep" / "mod.py").write_text(
        "value = 3\n", encoding="utf-8"
    )
    (tmp_path / ".pytest_cache").mkdir()
    (tmp_path / ".pytest_cache" / "lastfailed").write_text("{}\n", encoding="utf-8")

    by_path = source_closure.build(tmp_path).by_path()

    assert by_path[".venv"].classification is Classification.UNSCANNED
    assert by_path[".venv"].reason.startswith("environment_directory: .venv/")
    assert by_path[".pytest_cache"].classification is Classification.UNSCANNED
    enumerated = [path for path in by_path if path.startswith((".venv/", ".pytest_cache/"))]
    assert enumerated == [], f"environment contents must not be enumerated: {enumerated}"


def test_run_output_under_the_state_directory_is_accounted_but_not_enumerated(
    tmp_path: Path,
) -> None:
    build_tree(tmp_path)
    (tmp_path / ".hubbleops" / "artifacts" / "run").mkdir(parents=True)
    (tmp_path / ".hubbleops" / "artifacts" / "run" / "ledger.json").write_text(
        "{}\n", encoding="utf-8"
    )
    (tmp_path / ".hubbleops" / "surface.yml").write_text("rules: []\n", encoding="utf-8")

    by_path = source_closure.build(tmp_path).by_path()

    assert by_path[".hubbleops/artifacts"].classification is Classification.UNSCANNED
    assert by_path[".hubbleops/artifacts"].reason.startswith("state_output:")
    assert ".hubbleops/artifacts/run/ledger.json" not in by_path
    assert by_path[".hubbleops/surface.yml"].classification is Classification.INSIDE


def test_excluded_directory_identity_does_not_depend_on_its_contents(tmp_path: Path) -> None:
    build_tree(tmp_path)
    (tmp_path / ".venv").mkdir()
    (tmp_path / ".venv" / "first.py").write_text("value = 1\n", encoding="utf-8")
    before = source_closure.build(tmp_path).tree_hash()

    (tmp_path / ".venv" / "second.py").write_text("value = 2\n", encoding="utf-8")
    after = source_closure.build(tmp_path).tree_hash()

    assert before == after, "rebuilding a local environment must not invalidate the proof scope"
