from __future__ import annotations

from pathlib import Path

import pytest

from hubbleops.closure import source_closure
from hubbleops.closure.source_closure import Classification


def build_tree(root: Path) -> None:
    (root / "src").mkdir(parents=True)
    (root / "src" / "app.py").write_text("value = 1\n", encoding="utf-8")
    (root / "node_modules" / "pkg").mkdir(parents=True)
    (root / "node_modules" / "pkg" / "index.js").write_text(
        "module.exports = {};\n", encoding="utf-8"
    )
    (root / "build").mkdir()
    (root / "build" / "out.js").write_text("var x = 1;\n", encoding="utf-8")
    (root / "src" / "schema_pb2.py").write_text("SERIALIZED = b''\n", encoding="utf-8")
    (root / "src" / "marked.py").write_text("# @generated by a tool\nvalue = 2\n", encoding="utf-8")
    (root / "assets").mkdir()
    (root / "assets" / "logo.png").write_bytes(b"\x89PNG\x00\x00binary")
    (root / "assets" / "blob.dat").write_bytes(b"\x00\x01\x02opaque")


def test_every_path_gets_exactly_one_classification(tmp_path: Path) -> None:
    build_tree(tmp_path)
    closure = source_closure.build(tmp_path)
    paths = [entry.path for entry in closure.entries]
    assert len(paths) == len(set(paths))
    assert set(paths) == {
        "assets/blob.dat",
        "assets/logo.png",
        "build/out.js",
        "node_modules/pkg/index.js",
        "src/app.py",
        "src/marked.py",
        "src/schema_pb2.py",
    }


def test_classifications_follow_the_documented_precedence(tmp_path: Path) -> None:
    build_tree(tmp_path)
    by_path = source_closure.build(tmp_path).by_path()
    assert by_path["src/app.py"].classification is Classification.INSIDE
    assert by_path["node_modules/pkg/index.js"].classification is Classification.VENDORED
    assert by_path["build/out.js"].classification is Classification.GENERATED
    assert by_path["src/schema_pb2.py"].classification is Classification.GENERATED
    assert by_path["src/marked.py"].classification is Classification.GENERATED
    assert by_path["assets/logo.png"].classification is Classification.UNSCANNED
    assert by_path["assets/blob.dat"].classification is Classification.UNSCANNED


def test_binary_media_and_opaque_binaries_are_told_apart(tmp_path: Path) -> None:
    build_tree(tmp_path)
    by_path = source_closure.build(tmp_path).by_path()
    assert by_path["assets/logo.png"].reason.startswith("binary_media")
    assert by_path["assets/blob.dat"].reason.startswith("binary_opaque")


def test_every_entry_carries_a_reason(tmp_path: Path) -> None:
    build_tree(tmp_path)
    for entry in source_closure.build(tmp_path).entries:
        assert entry.reason


def test_submodule_paths_are_classified_from_gitmodules(tmp_path: Path) -> None:
    (tmp_path / "libs" / "shared").mkdir(parents=True)
    (tmp_path / "libs" / "shared" / "core.py").write_text("value = 1\n", encoding="utf-8")
    (tmp_path / ".gitmodules").write_text(
        '[submodule "shared"]\n\tpath = libs/shared\n\turl = https://example.test/shared.git\n',
        encoding="utf-8",
    )
    by_path = source_closure.build(tmp_path).by_path()
    assert by_path["libs/shared/core.py"].classification is Classification.SUBMODULE


def test_a_gitlink_directory_is_a_submodule(tmp_path: Path) -> None:
    (tmp_path / "vendored-repo").mkdir()
    (tmp_path / "vendored-repo" / ".git").write_text(
        "gitdir: ../.git/modules/x\n", encoding="utf-8"
    )
    (tmp_path / "vendored-repo" / "main.py").write_text("value = 1\n", encoding="utf-8")
    by_path = source_closure.build(tmp_path).by_path()
    assert by_path["vendored-repo/main.py"].classification is Classification.SUBMODULE


def test_oversize_files_are_unscanned_not_silently_skipped(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    (tmp_path / "big.txt").write_text("x" * 64, encoding="utf-8")
    monkeypatch.setattr(source_closure, "MAX_SCAN_BYTES", 8)
    entry = source_closure.build(tmp_path).by_path()["big.txt"]
    assert entry.classification is Classification.UNSCANNED
    assert entry.reason.startswith("oversize")


def test_the_git_control_directory_is_reported_not_hidden(tmp_path: Path) -> None:
    (tmp_path / ".git").mkdir()
    (tmp_path / ".git" / "config").write_text("[core]\n", encoding="utf-8")
    (tmp_path / "app.py").write_text("value = 1\n", encoding="utf-8")
    closure = source_closure.build(tmp_path)
    assert [entry.path for entry in closure.entries] == ["app.py"]
    assert closure.control_directories == (".git",)


def test_tree_hash_binds_content_even_without_git(tmp_path: Path) -> None:
    (tmp_path / "app.py").write_text("value = 1\n", encoding="utf-8")
    first = source_closure.build(tmp_path)
    assert first.repo_sha is None
    assert first.tree_hash() == source_closure.build(tmp_path).tree_hash()
    (tmp_path / "app.py").write_text("value = 2\n", encoding="utf-8")
    assert source_closure.build(tmp_path).tree_hash() != first.tree_hash()


def test_scannable_excludes_unscanned_entries(tmp_path: Path) -> None:
    build_tree(tmp_path)
    closure = source_closure.build(tmp_path)
    assert all(entry.carries_source() for entry in closure.scannable())
    assert len(closure.scannable()) + len(closure.unscanned()) == len(closure.entries)


def test_a_missing_root_is_an_error_not_an_empty_closure(tmp_path: Path) -> None:
    with pytest.raises((NotADirectoryError, FileNotFoundError)):
        source_closure.build(tmp_path / "absent")
